import { Hono } from "hono";
import { csrfFor,csrfValid } from "../http/cookies";
import type { AppEnv } from "../types";
import { resourceDetailPage,resourceFormPage,resourceListPage,resourceReviewsPage } from "../views/resources";

export type ResourceRow={id:number;title:string;res_type:string;description:string;original_name:string;status:string;admin_note:string;created_at:string;production_id:number|null;production_title:string|null;uploader_id:number|null;uploader_name:string|null};
export const resourceRoutes=new Hono<AppEnv>();
resourceRoutes.use("*",async(c,next)=>{if(!c.get("user"))return c.redirect(`/login?next=${encodeURIComponent(c.req.path)}`);await next()});
const adminDenied=(c:any)=>c.get("user")?.role==="admin"?null:c.text("没有管理员权限。",403);

resourceRoutes.get("/resources",async c=>{const rows=await c.env.DB.prepare(`SELECT r.id,r.title,r.res_type,r.description,r.original_name,r.status,r.admin_note,r.created_at,r.production_id,p.title production_title,r.uploader_id,u.username uploader_name FROM resource r LEFT JOIN production p ON p.id=r.production_id LEFT JOIN user u ON u.id=r.uploader_id WHERE r.status='approved' ORDER BY r.created_at DESC,r.id DESC`).all<ResourceRow>();return c.html(resourceListPage(rows.results,c.get("user")!,await csrfFor(c)))});
resourceRoutes.get("/my-resources",async c=>{const u=c.get("user")!;const rows=await c.env.DB.prepare(`SELECT r.id,r.title,r.res_type,r.description,r.original_name,r.status,r.admin_note,r.created_at,r.production_id,p.title production_title,r.uploader_id,u.username uploader_name FROM resource r LEFT JOIN production p ON p.id=r.production_id LEFT JOIN user u ON u.id=r.uploader_id WHERE r.uploader_id=? ORDER BY r.id DESC`).bind(u.id).all<ResourceRow>();return c.html(resourceListPage(rows.results,u,await csrfFor(c),true))});
resourceRoutes.get("/resources/submit",async c=>{const u=c.get("user")!;if(u.role==="user")return c.text("认证队员或管理员才能提交资料。",403);const productions=await c.env.DB.prepare("SELECT id,title FROM production ORDER BY year DESC,id DESC").all<{id:number;title:string}>();return c.html(resourceFormPage(productions.results,await csrfFor(c)))});
resourceRoutes.post("/resources/submit",async c=>{const u=c.get("user")!;if(u.role==="user")return c.text("认证队员或管理员才能提交资料。",403);const f=await c.req.formData();if(!csrfValid(c,f.get("csrf")))return c.text("请求已失效。",400);const title=String(f.get("title")??"").trim(),original=String(f.get("original_name")??"").trim(),type=String(f.get("res_type")??"other"),description=String(f.get("description")??"").trim();const productionText=String(f.get("production_id")??"");const production=productionText?Number(productionText):null;if(!title||title.length>100||!original||original.length>255||description.length>2000||!["video","script","photo","audio","other"].includes(type))return c.text("请检查资料名称、类型、说明和文件名。",400);if(production!==null&&!await c.env.DB.prepare("SELECT id FROM production WHERE id=?").bind(production).first())return c.text("作品不存在。",400);const status=u.role==="admin"?"approved":"pending";const safeName=original.replace(/[^a-zA-Z0-9._-]/g,"_")||"resource";const key=`pending/${crypto.randomUUID()}/${safeName}`;await c.env.DB.prepare("INSERT INTO resource(production_id,status,uploader_id,title,res_type,description,filename,original_name) VALUES(?,?,?,?,?,?,?,?)").bind(production,status,u.id,title,type,description,key,original).run();return c.redirect("/my-resources",303)});
resourceRoutes.get("/resources/:id",async c=>{const u=c.get("user")!;const row=await c.env.DB.prepare(`SELECT r.id,r.title,r.res_type,r.description,r.original_name,r.status,r.admin_note,r.created_at,r.production_id,p.title production_title,r.uploader_id,u.username uploader_name FROM resource r LEFT JOIN production p ON p.id=r.production_id LEFT JOIN user u ON u.id=r.uploader_id WHERE r.id=?`).bind(Number(c.req.param("id"))).first<ResourceRow>();if(!row)return c.text("资料不存在。",404);if(row.status!=="approved"&&row.uploader_id!==u.id&&u.role!=="admin")return c.text("没有权限查看这份资料。",403);return c.html(resourceDetailPage(row,u))});
resourceRoutes.get("/admin/resources/reviews",async c=>{const denied=adminDenied(c);if(denied)return denied;const rows=await c.env.DB.prepare(`SELECT r.id,r.title,r.res_type,r.description,r.original_name,r.status,r.admin_note,r.created_at,r.production_id,p.title production_title,r.uploader_id,u.username uploader_name FROM resource r LEFT JOIN production p ON p.id=r.production_id LEFT JOIN user u ON u.id=r.uploader_id WHERE r.status='pending' ORDER BY r.id`).all<ResourceRow>();return c.html(resourceReviewsPage(rows.results,await csrfFor(c)))});
resourceRoutes.post("/admin/resources/:id/review",async c=>{const denied=adminDenied(c);if(denied)return denied;const f=await c.req.formData();if(!csrfValid(c,f.get("csrf")))return c.text("请求已失效。",400);const decision=f.get("decision")==="approve"?"approved":"rejected";const note=String(f.get("admin_note")??"").trim();if(decision==="rejected"&&!note)return c.text("驳回时必须填写理由。",400);const result=await c.env.DB.prepare("UPDATE resource SET status=?,admin_note=? WHERE id=? AND status='pending'").bind(decision,note,Number(c.req.param("id"))).run();if(result.meta.changes!==1)return c.text("资料不存在或已处理。",404);return c.redirect("/admin/resources/reviews",303)});
