import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
const files = [
  "app.css",
  "experience.css",
  "fonts.css",
  "redesign.css",
  "app.js",
  "experience.js",
  "curtain-boot.js",
  "upload.js",
  "review.js",
  "images/elephant-mascot-360-v1.webp",
];
mkdirSync("public/assets", { recursive: true });
mkdirSync("src/generated", { recursive: true });
const manifest = {};
for (const file of files) {
  const bytes = readFileSync("public/" + file);
  const hash = createHash("sha256").update(bytes).digest("hex").slice(0, 16);
  const name = file.replaceAll("/", "-").replace(/(\.[^.]+)$/, `.${hash}$1`);
  if (!existsSync("public/assets/" + name)) writeFileSync("public/assets/" + name, bytes);
  manifest["/" + file] = "/assets/" + name;
}
// Existing hashed files remain available for pages still open during deployment.
writeFileSync(
  "src/generated/assets.ts",
  "// Generated by npm run assets:build.\nexport const assets: Record<string,string> = " +
    JSON.stringify(manifest, null, 2) +
    ";\n",
);
// The blank XLSX is bundled for authenticated downloads, not exposed as a static asset.
writeFileSync(
  "src/generated/credit-template.ts",
  "// Generated by npm run assets:build.\nexport const creditTemplate = " +
    JSON.stringify(readFileSync("templates/production-credit-import-v2.xlsx").toString("base64")) +
    ";\n",
);
