CREATE TABLE IF NOT EXISTS poc_entry (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    note TEXT NOT NULL CHECK (length(note) BETWEEN 1 AND 80),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
